/*
 * Copyright 2021 J.B. Slade.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mms.dialogs;

import com.mms.MMS;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.io.StringWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTML;
import javax.swing.text.html.HTML.Tag;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author J.B. Slade
 */
public class ScheduleDialog extends javax.swing.JInternalFrame {
    
    private final int row;
    private final JTable table;
    private final HTMLEditorKit htmlKit;
    private final HTMLDocument htmlDoc;
    
    public ScheduleDialog(JTable t, int r) {
        initComponents();
        table = t;
        row = r;
        htmlKit = (HTMLEditorKit) descPane.getEditorKit();
        htmlDoc = (HTMLDocument) descPane.getDocument();
        getRootPane().setDefaultButton(continueButton);
        
        //Set right click listeners
        nameField.addMouseListener(MMS.getMouseListener());
        descPane.addMouseListener(MMS.getMouseListener());
        
        //Set underline button
        Font font = underlineButton.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        font = font.deriveFont(attributes);
        underlineButton.setFont(font);
        
        //Set locations
        ResultSet rs = MMS.select("SELECT id, location_name FROM locations WHERE archived = 'N'");
        try {
            while(rs.next()){
                locationCombo.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Set assets
        rs = MMS.select("SELECT id, asset_name FROM assets WHERE archived = 'N'");
        try {
            while(rs.next()){
                assetCombo.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Set types
        rs = MMS.select("SELECT custom_value FROM custom_fields WHERE custom_type = 'schedule_type'");
        try {
            while(rs.next()){
                typeCombo.addItem(rs.getString(1));
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Edit
        if (r == -1){
            continueButton.setText("Save");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        markDownTools = new javax.swing.JToolBar();
        boldButton = new javax.swing.JButton();
        italicsButton = new javax.swing.JButton();
        underlineButton = new javax.swing.JButton();
        bulletButton = new javax.swing.JButton();
        descScroll = new javax.swing.JScrollPane();
        descPane = new javax.swing.JTextPane();
        leftPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        assetLabel = new javax.swing.JLabel();
        assetCombo = new javax.swing.JComboBox<>();
        rightPanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        freqLabel = new javax.swing.JLabel();
        freqCombo = new javax.swing.JComboBox<>();
        locationLabel = new javax.swing.JLabel();
        locationCombo = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("New Task");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dialogs/schedule.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        continueButton.setText("Add");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        markDownTools.setFloatable(false);
        markDownTools.setRollover(true);

        boldButton.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        boldButton.setText("B");
        boldButton.setFocusable(false);
        boldButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boldButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boldButtonActionPerformed(evt);
            }
        });
        markDownTools.add(boldButton);

        italicsButton.setFont(new java.awt.Font("Tahoma", 2, 17)); // NOI18N
        italicsButton.setText("I");
        italicsButton.setFocusable(false);
        italicsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        italicsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        italicsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italicsButtonActionPerformed(evt);
            }
        });
        markDownTools.add(italicsButton);

        underlineButton.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        underlineButton.setText("U");
        underlineButton.setFocusable(false);
        underlineButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        underlineButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        underlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underlineButtonActionPerformed(evt);
            }
        });
        markDownTools.add(underlineButton);

        bulletButton.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        bulletButton.setText("•");
        bulletButton.setFocusable(false);
        bulletButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bulletButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        markDownTools.add(bulletButton);

        descPane.setContentType("text/html"); // NOI18N
        descScroll.setViewportView(descPane);

        nameLabel.setText("Name:");

        dateLabel.setText("Start Date:");

        assetLabel.setText("Asset:");

        assetCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Asset" }));
        assetCombo.setPreferredSize(nameField.getPreferredSize());

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nameLabel)
                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addComponent(dateLabel)
                .addComponent(dateField))
            .addComponent(assetLabel)
            .addComponent(assetCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPanel.setPreferredSize(leftPanel.getPreferredSize());

        typeLabel.setText("Type:");

        typeCombo.setPreferredSize(nameField.getPreferredSize());

        freqLabel.setText("Frequency:");

        freqCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly", "Quarterly", "Bianually", "Anually" }));
        freqCombo.setPreferredSize(nameField.getPreferredSize());

        locationLabel.setText("Location:");

        locationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Location" }));
        locationCombo.setPreferredSize(nameField.getPreferredSize());

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(typeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(freqCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeLabel)
                    .addComponent(freqLabel)
                    .addComponent(locationLabel))
                .addGap(0, 111, Short.MAX_VALUE))
            .addComponent(locationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(typeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freqLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freqCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continueButton))
                    .addComponent(markDownTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descScroll)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markDownTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(descScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        
    }//GEN-LAST:event_continueButtonActionPerformed

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        getRootPane().setDefaultButton(continueButton);
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void boldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldButtonActionPerformed
        //formatSelection("<b>", "</b>");
        format();
    }//GEN-LAST:event_boldButtonActionPerformed

    private void italicsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicsButtonActionPerformed
        formatSelection("<i>", "</i>");
    }//GEN-LAST:event_italicsButtonActionPerformed

    private void underlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underlineButtonActionPerformed
        formatSelection("<u>", "</u>");
    }//GEN-LAST:event_underlineButtonActionPerformed

    private void format(){
        String text = descPane.getSelectedText();
        int start = descPane.getSelectionStart(), end = descPane.getSelectionEnd();
        descPane.replaceSelection("");
            try {
                htmlKit.insertHTML(htmlDoc, start, "<b>"+text, 0, 0, HTML.Tag.B);
            } catch (BadLocationException | IOException ex) {
                Logger.getLogger(ScheduleDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            descPane.setSelectionStart(start);
            descPane.setSelectionEnd(end);
    }
    
    private void formatSelection(String startTag, String endTag){
        String text = descPane.getSelectedText(); 
        if(text != null){
            int start = descPane.getSelectionStart(), end = descPane.getSelectionEnd();

            //Check if text contains other tags
            try (StringWriter w = new StringWriter()) {
                htmlKit.write(w, htmlDoc, start, end-start);
                String tags = w.toString();
                if(tags.contains("<b>")){
                    startTag = startTag + "<b>";
                    endTag = "</b>" + endTag;
                }
                if(tags.contains("<i>")){
                    startTag = startTag + "<i>";
                    endTag = "</i>" + endTag;
                }
                if(tags.contains("<u>")){
                    startTag = startTag + "<u>";
                    endTag = "</u>" + endTag;
                }
            } catch (IOException | BadLocationException ex) {
                Logger.getLogger(ScheduleDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            descPane.replaceSelection("");
            try {
                htmlKit.insertHTML(htmlDoc, start, startTag+text+endTag, 0, 0, null);
            } catch (BadLocationException | IOException ex) {
                Logger.getLogger(ScheduleDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            descPane.setSelectionStart(start);
            descPane.setSelectionEnd(end+1);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> assetCombo;
    private javax.swing.JLabel assetLabel;
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton boldButton;
    private javax.swing.JButton bulletButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextPane descPane;
    private javax.swing.JScrollPane descScroll;
    private javax.swing.JComboBox<String> freqCombo;
    private javax.swing.JLabel freqLabel;
    private javax.swing.JButton italicsButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JComboBox<String> locationCombo;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JToolBar markDownTools;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton underlineButton;
    // End of variables declaration//GEN-END:variables
}
