package com.mms.locations;

import com.mms.MMS;
import com.sun.glass.events.KeyEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class LocationDialog extends javax.swing.JInternalFrame {
    
    private int row = -1;
    private final JTable table;
    
    public LocationDialog(JTable t) {
        initComponents();
        table = t;

    }
    
    public LocationDialog(JTable t, int r) {
        initComponents();
        table = t;
        row = r;
        setTitle("Edit Location");
        button.setText("Save");
        nameField.setText(t.getModel().getValueAt(row, 1).toString());
        descField.setText(t.getModel().getValueAt(row, 2).toString());
        nameField.requestFocus();
        nameField.selectAll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        descScroll = new javax.swing.JScrollPane();
        descField = new javax.swing.JTextArea();
        button = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("New Location");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iframes/locations.png"))); // NOI18N

        nameLabel.setText("Location Name:");

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
        });

        descLabel.setText("Location Description:");

        descField.setColumns(20);
        descField.setRows(5);
        descField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
        });
        descScroll.setViewportView(descField);

        button.setText("Add");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button))
                    .addComponent(nameField)
                    .addComponent(nameLabel)
                    .addComponent(descLabel)
                    .addComponent(descScroll))
                .addContainerGap())
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String name = nameField.getText(), desc = descField.getText();
        if(name.isEmpty()) nameField.requestFocus();
        else if(desc.isEmpty()) descField.requestFocus();
        else{
            if(row == -1){ //New location
                    //Get next no
                    int locNum = 0;
                    for(int i = 0; i < table.getRowCount(); i++){
                        int n = Integer.parseInt(table.getValueAt(i, 0).toString());
                        if(n > locNum) locNum = n;
                    }
                    locNum++;
                    //Insert into DB
                    MMS.executeQuery("INSERT INTO Locations (LocationNo, LocationName, LocationDescription, Archived) VALUES (?, ?, ?, 'N')",
                            new Object[]{locNum, name, desc});
                    //Insert into table
                    Object [] o = {locNum, name, desc};
                    DefaultTableModel m = (DefaultTableModel)table.getModel();
                    m.insertRow(0, o);
                    //Select new row
                    table.setRowSelectionInterval(0, 0);
                }
            else{ //Edit location
                //Get selected number
                int locNum = Integer.parseInt(table.getValueAt(row, 0).toString());
                //Update database
                MMS.executeQuery("UPDATE Locations SET LocationName = ?, LocationDescription = ? WHERE LocationNo = ?",
                        new Object[]{name, desc, locNum});
                //Update table
                table.setValueAt(name, row, 1);
                table.setValueAt(desc, row, 2);
                //Select updated row
                table.setRowSelectionInterval(row, row);
            }
            dispose();
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buttonActionPerformed(null);
        }
    }//GEN-LAST:event_nameFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton button;
    private javax.swing.JTextArea descField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JScrollPane descScroll;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
