/*
 * Copyright 2021 J.B. Slade.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mms.iframes;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.mms.Database;
import com.mms.MMS;
import com.mms.utilities.TableTools;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J.B. Slade
 */
public class WOCloseFrame extends javax.swing.JInternalFrame {

    DateTimePicker startTimePicker, endTimePicker;
    
    public WOCloseFrame() {
        initComponents();
        getRootPane().setDefaultButton(continueButton);
        
        //Set right click listeners
        actionArea.addMouseListener(MMS.getMouseListener());
        
        //Set parts
        Object [] o = new Object[4];
        DefaultTableModel t = (DefaultTableModel)partsTable.getModel();
        ResultSet rs = Database.select("SELECT id, part_name, part_qty FROM parts");
        try {
            while(rs.next()){
                o[0] = rs.getObject(1).toString().trim();
                o[1] = rs.getObject(2).toString().trim();
                o[2] = rs.getInt(3);
                o[3] = 0;
                t.addRow(o);
            }
        } catch (SQLException ex) {
            Logger.getLogger(WOCloseFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        TableTools.format(partsTable);
        TableTools.resize(partsTable);
        
        //Set date pickers
        //Time settings
        TimePickerSettings timeSettings = new TimePickerSettings();
        timeSettings.setFormatForDisplayTime(DateTimeFormatter.ISO_LOCAL_TIME);
        timeSettings.setDisplayToggleTimeMenuButton(true);
        timeSettings.setAllowEmptyTimes(false);
        //Date settings
        DatePickerSettings startDateSettings = new DatePickerSettings();
        startDateSettings.setFormatForDatesCommonEra(DateTimeFormatter.ISO_LOCAL_DATE);
        startDateSettings.setBorderCalendarPopup(actionScrollPane.getBorder());
        startDateSettings.setAllowEmptyDates(false);
        DatePickerSettings endDateSettings = new DatePickerSettings();
        endDateSettings.setFormatForDatesCommonEra(DateTimeFormatter.ISO_LOCAL_DATE);
        endDateSettings.setBorderCalendarPopup(actionScrollPane.getBorder());
        endDateSettings.setAllowEmptyDates(false);
        //Start time picker
        startTimePicker = new DateTimePicker(startDateSettings, timeSettings);
        startTimePicker.getDatePicker().getComponentDateTextField().setBorder(actionScrollPane.getBorder());
        startTimePicker.getTimePicker().getComponentTimeTextField().setBorder(actionScrollPane.getBorder());
        startTimePicker.getDatePicker().setPreferredSize(startTimePicker.getTimePicker().getPreferredSize());
        startTimePanel.add(startTimePicker);
        //End time picker
        endTimePicker = new DateTimePicker(endDateSettings, timeSettings);
        endTimePicker.getDatePicker().getComponentDateTextField().setBorder(actionScrollPane.getBorder());
        endTimePicker.getTimePicker().getComponentTimeTextField().setBorder(actionScrollPane.getBorder());
        endTimePicker.getDatePicker().setPreferredSize(endTimePicker.getTimePicker().getPreferredSize());
        endTimePanel.add(endTimePicker);
        startTimePanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        actionLabel = new javax.swing.JLabel();
        actionScrollPane = new javax.swing.JScrollPane();
        actionArea = new javax.swing.JTextArea();
        partsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        partsTable = new javax.swing.JTable();
        startTimeLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        startTimePanel = new javax.swing.JPanel();
        endTimePanel = new javax.swing.JPanel();
        endTimeLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Close Work Order #");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dialogs/workOrders.png"))); // NOI18N

        actionLabel.setText("Actions Performed:");

        actionArea.setColumns(20);
        actionArea.setRows(3);
        actionScrollPane.setViewportView(actionArea);

        partsLabel.setText("Parts Used:");

        partsTable.setAutoCreateRowSorter(true);
        partsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " #", " Name", " In Stock", " Used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(partsTable);

        startTimeLabel.setText("Start Time:");

        continueButton.setText("Done");

        startTimePanel.setDoubleBuffered(false);
        startTimePanel.setPreferredSize(new java.awt.Dimension(0, 23));
        startTimePanel.setLayout(new java.awt.GridLayout());

        endTimePanel.setPreferredSize(new java.awt.Dimension(0, 23));
        endTimePanel.setLayout(new java.awt.GridLayout());

        endTimeLabel.setText("End Time:");

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionScrollPane)
                    .addComponent(actionLabel)
                    .addComponent(partsLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(continueButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(endTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(endTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continueButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea actionArea;
    private javax.swing.JLabel actionLabel;
    private javax.swing.JScrollPane actionScrollPane;
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel endTimeLabel;
    private javax.swing.JPanel endTimePanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel partsLabel;
    private javax.swing.JTable partsTable;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JPanel startTimePanel;
    // End of variables declaration//GEN-END:variables
}
